// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from '/home/ljp/data/ljp/git/work-edtechhub/work-topic-selection/client/work-topic-selection-react/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import FormOutlined from '/home/ljp/data/ljp/git/work-edtechhub/work-topic-selection/client/work-topic-selection-react/node_modules/@ant-design/icons/es/icons/FormOutlined';
import BarChartOutlined from '/home/ljp/data/ljp/git/work-edtechhub/work-topic-selection/client/work-topic-selection-react/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
import FieldTimeOutlined from '/home/ljp/data/ljp/git/work-edtechhub/work-topic-selection/client/work-topic-selection-react/node_modules/@ant-design/icons/es/icons/FieldTimeOutlined';
import CheckSquareOutlined from '/home/ljp/data/ljp/git/work-edtechhub/work-topic-selection/client/work-topic-selection-react/node_modules/@ant-design/icons/es/icons/CheckSquareOutlined';
export default { HomeOutlined, FormOutlined, BarChartOutlined, FieldTimeOutlined, CheckSquareOutlined };
